name: ReservaSports
description: "Aplicaci√≥n de reservas de canchas deportivas"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  url_launcher: ^6.1.10
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.7.0
  intl: ^0.18.1
  font_awesome_flutter: ^10.4.0
  fl_chart: ^0.69.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  mailer: ^6.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   

flutter_launcher_icons:             
  android: true
  ios: true
  image_path: "lib/images/logoReservaSports.jpg"
  adaptive_icon_foreground: "lib/images/logoReservaSports.jpg"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - lib/images/  
